[package]
name = "pro-dj-link"
version = "0.1.0"
edition = "2021"

[features]
default = ["sync"]
sync = []

[dependencies]
bitflags = "1.3.2"
thiserror = "1"
async-std = { version = "1.12", optional = true }
tokio = { version = "1.37", optional = true, features = ["net"] }
tracing = "0.1"
